(function(){
'use strict';
const root=document.getElementById('app'),modal=document.getElementById('modal');
const cfg=window.PLANB_CONFIG||{};
const cities=[
 {city:'佛山',date:'9月18日',temp:'23 ~ 30℃',weather:'小雨',tip:'请携带雨具'},
 {city:'济南',date:'9月22日',temp:'17 ~ 28℃',weather:'多云',tip:'早晚温差较大'},
 {city:'上海',date:'10月21日',temp:'--',weather:'待更新',tip:'临近活动日期更新天气'}];
const store={get(k,d){try{return JSON.parse(localStorage.getItem('bochu_web_'+k))??d}catch(e){return d}},set(k,v){localStorage.setItem('bochu_web_'+k,JSON.stringify(v))}};
const state={city:store.get('city','上海'),profile:store.get('profile',null),application:store.get('application',null),lucky:store.get('lucky',''),canInvite:store.get('canInvite',true)};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
function nav(active){return `<nav class="bottom"><button class="nav ${active==='home'?'active':''}" data-go="home">◇<br>共创会</button><button class="nav-lucky" data-go="lottery">LUCKY<br>抽奖码</button><button class="nav ${active==='profile'?'active':''}" data-go="profile">♙<br>个人中心</button></nav>`}
function shell(html,active='home'){root.innerHTML=`<div class="shell"><div class="content">${html}</div>${nav(active)}</div>`}
function status(){if(!state.application)return '未登记';return ({PENDING:'审核中',APPROVED:'已审核',REJECTED:'未通过'})[state.application.status]||'未登记'}
function home(){const w=cities.find(x=>x.city===state.city)||cities[2];shell(`
 <section class="hero"><img src="assets/banner.jpg"><div class="shade"></div><div class="weather">${w.temp}<small>${w.weather}</small></div><div class="hero-copy"><div class="eyebrow">BOCHU WELCOME</div><h1>共创会</h1><div class="gold-rule"></div><div class="hero-sub">柏楚2026价值共创峰会</div></div></section>
 <section class="panel"><div class="tabs">${cities.map(c=>`<button class="tab ${c.city===state.city?'active':''}" data-city="${c.city}">${c.city}</button>`).join('')}</div><div class="trip">● <b>共创会当日行程</b> · ${w.city} · ${w.weather} ${w.temp} · ${w.tip}</div><div class="facts"><div class="fact"><small>DATE</small><strong>${w.date}</strong></div><div class="fact"><small>VENUE</small><strong>${w.city}</strong></div><div class="fact"><small>登记状态</small><strong class="status">${status()}</strong></div></div>${state.application&&state.application.status==='APPROVED'?`<div class="invite-slip"><div class="invite-seal">贵宾</div><div><small>EXCLUSIVE INVITATION</small><b>受邀场次 · ${esc(state.application.city)}场</b></div></div>`:''}</section>
 <div class="grid"><button class="feature primary" data-go="apply"><span class="num">01</span><b>参会登记</b><span class="meta">APPLICATION</span></button><button class="feature lucky" data-go="lottery"><span class="num">02</span><b>抽奖码</b><span class="meta">LUCKY DRAW</span></button></div>
 ${state.canInvite?'<button class="manager" data-go="invitations"><b>我的邀请</b><small>INVITATION MANAGEMENT</small></button>':''}
 <section class="service"><div class="section-head"><span>参会服务</span><small>SERVICES</small></div><button class="menu" data-go="letter"><span>03</span><b>电子邀请函</b></button><button class="menu" data-go="agenda"><span>04</span><b>大会议程</b></button><button class="menu" data-go="route"><span>05</span><b>交通路线</b></button></section>`,'home');
 if(!store.get('privacy',false)) privacy();}
function privacy(){modal.innerHTML=`<div class="privacy-mask"><div class="privacy-card"><div class="eyebrow">PRIVACY NOTICE</div><h2>尊敬的贵宾</h2><p>为提供邀请函、参会登记及抽奖码服务，我们需要处理您主动提交的个人信息。请阅读相关协议后自主选择是否同意。</p><label class="check"><input id="privacyCheck" type="checkbox"><span>我已阅读并同意<a href="#agreement">《用户服务协议》</a>、<a href="#privacy">《隐私政策》</a>及<a href="#rules">《抽奖活动说明》</a>。</span></label><br><button id="privacyConfirm" class="btn">同意并进入</button></div></div>`}
function apply(){if(state.application){applicationResult();return}const city=state.city;const profile=state.profile||{};shell(`${header('INVITATION','贵宾登记','确认邀请函，并完善您的参会信息')}<form id="applyForm"><section class="card"><div class="card-title">主要联系人</div><div class="field"><label>同行人数</label><select id="count">${[1,2,3,4,5].map(n=>`<option>${n}</option>`).join('')}</select></div><div id="guests"></div><div class="field"><label>参会备注</label><textarea name="reason" placeholder="如有接待偏好可简要填写（选填）"></textarea></div></section><div class="form-actions"><button class="btn" type="submit">确认提交邀请函</button></div></form>`);renderGuests(1,profile);}
function renderGuests(count,profile={}){const box=document.getElementById('guests');if(!box)return;box.innerHTML=Array.from({length:count},(_,i)=>`<div class="guest"><div class="guest-name">${i?'同行人 '+(i+1):'主要联系人'}</div><div class="field"><label>姓名 *</label><input name="name${i}" required value="${i?'':esc(profile.name||'')}"></div><div class="field"><label>公司</label><input name="company${i}"></div><div class="row"><div class="field"><label>性别 *</label><select name="gender${i}"><option>男</option><option>女</option></select></div><div class="field"><label>职位</label><input name="position${i}"></div></div><div class="field"><label>手机号 *</label><input name="phone${i}" required inputmode="numeric" maxlength="11" value="${i?'':esc(profile.phone||'')}"></div><div class="field"><label>住宿要求</label><select name="stay${i}"><option>无需住宿</option><option>需要住宿</option></select></div></div>`).join('')}
function applicationResult(){const a=state.application;const txt=a.status==='APPROVED'?'审核已通过':a.status==='REJECTED'?'审核未通过':'已提交，等待审核';shell(`${header('REGISTRATION','登记状态','')}<section class="card"><div class="eyebrow">REGISTRATION STATUS</div><h2>${txt}</h2><p>${a.status==='APPROVED'?'您的参会登记已审核通过，可以前往领取抽奖码。':'会务团队正在审核您的参会登记，通过后可以前往领取抽奖码。'}</p><div class="invite-slip"><div class="invite-seal">贵宾</div><b>贵宾 · ${esc(a.guests[0].name)}</b></div>${a.status==='APPROVED'?'<button class="btn" data-go="lottery">领取抽奖码</button><br><br>':''}<button class="btn secondary" data-go="home">返回共创会</button></section>`)}
function lottery(){shell(`<div class="lottery-page"><div class="lottery-hero"><img src="assets/lottery-shipyard-v2.jpg"><div class="shade"></div><div class="lottery-title"><h1>幸运抽奖</h1><small>LUCKY DRAW CEREMONY</small></div></div><section class="ticket"><div class="eyebrow">EXCLUSIVE LUCKY CODE</div><h2>专属抽奖码</h2><div id="machine" class="machine"><div class="reels">${(state.lucky||'0000').split('').map(d=>`<div class="reel">${d}</div>`).join('')}</div><div class="result-seal">${state.lucky?'LUCKY':''}</div></div><p id="notice" class="notice">${state.lucky?'您的抽奖码已经生成，等待开奖。':'请提前抽取您的专属号码，并静候会场开奖。'}</p><button id="draw" class="btn" ${state.lucky?'disabled':''}>${state.lucky?'号码已抽取':'抽取号码'}</button><p><small>每位嘉宾仅有一次抽取机会</small></p><a href="#rules">查看《抽奖活动说明》</a></section></div>`)}
function invitations(){const invites=store.get('invites',null)||cities.map(c=>({city:c.city,code:code(),used:0}));store.set('invites',invites);shell(`${header('INVITATION MANAGEMENT','我的邀请','选择场次，转发专属邀请并管理登记名单')}<h3 style="margin:20px 14px">活动场次</h3>${invites.map(i=>`<section class="city-card"><h2>${i.city}场</h2><small>已登记 ${i.used} 人</small><div class="code">${i.code}</div><div class="actions"><button class="btn" data-copy="${i.code}">复制邀请链接</button><button class="btn secondary" data-qr="${i.code}">网页二维码</button></div><br><button class="btn" data-list="${i.city}">查看邀请列表 ›</button></section>`).join('')}`)}
function profile(){const p=state.profile;shell(`${header('BOCHU INVITATION','个人中心','')}<section class="profile-card"><small>贵宾档案</small><h2>${esc(p?.name||'尚未登录')}</h2><p>${esc(p?.gender||'')} ${p?.phone?' · '+esc(p.phone):''}</p></section>${state.application?`<section class="card"><div class="card-title">参会登记记录</div><p>${esc(state.application.city)}场 · ${status()}</p>${state.application.guests.map((g,i)=>`<div class="guest"><b>${i?'同行人 '+(i+1):'主要联系人'}</b><p>${esc(g.name)} · ${esc(g.gender)} · ${esc(g.phone)}</p><p>${esc(g.company||'未填写')} · ${esc(g.position||'未填写')}</p></div>`).join('')}</section>`:'<div class="empty">暂无参会登记记录</div>'}<section class="card"><p>我们尊重并保护您的个人信息。</p><a href="#agreement">《用户服务协议》</a> 及 <a href="#privacy">《隐私政策》</a></section>`,'profile')}
function service(type){const data={letter:['电子邀请函','诚挚邀请您莅临柏楚2026价值共创峰会，与行业伙伴共话价值、共见未来。'],agenda:['大会议程','签到与贵宾接待 · 主题分享 · 圆桌共创 · 晚宴及现场开奖'],route:['交通路线',`${state.city}场详细交通及停车信息将在活动开始前由会务团队更新。`]};const d=data[type];shell(`${header('BOCHU SERVICES',d[0],'参会服务')}<section class="card"><div class="card-title">${d[0]}</div><p style="line-height:2;color:#626a7a">${d[1]}</p><button class="btn secondary" data-go="home">返回首页</button></section>`)}
function textPage(type){const d={agreement:['用户服务协议','本服务用于柏楚2026价值共创峰会邀请、登记、会务及抽奖服务。用户应确保提交的信息真实、准确，并已取得同行人员授权。请妥善保管邀请链接及抽奖码，不得用于违法用途。'],privacy:['隐私政策','我们仅为身份确认、参会审核、会务联络、住宿安排及抽奖服务处理您主动提交的信息。相关信息原则上保存至活动结束后30天，并采取合理安全措施保护。'],rules:['抽奖活动说明','每位审核通过的参会嘉宾仅可抽取一次四位数字抽奖码。抽奖码用于现场开奖，最终结果以活动现场公布为准。']};const x=d[type];shell(`<article class="text-page"><button class="back" data-go="home">← 返回</button><h1>${x[0]}</h1>${Array(5).fill(`<p>${x[1]}</p>`).join('')}</article>`)}
function header(k,t,s){return `<header class="page-head"><img src="assets/banner.jpg"><div class="shade"></div><div class="page-title"><div class="eyebrow">${k}</div><h1>${t}</h1><small>${s}</small></div></header>`}
function code(){const chars='23456789ABCDEFGHJKLMNPQRSTUVWXYZ';return Array.from({length:8},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function route(){const name=(location.hash.slice(1)||'home').split('?')[0];modal.innerHTML='';if(['agreement','privacy','rules'].includes(name))return textPage(name);if(['letter','agenda','route'].includes(name))return service(name);({home,apply,lottery,invitations,profile}[name]||home)()}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){location.hash=go.dataset.go;return}const tab=e.target.closest('[data-city]');if(tab){state.city=tab.dataset.city;store.set('city',state.city);home();return}if(e.target.id==='privacyConfirm'){if(!document.getElementById('privacyCheck').checked)return toast('请先勾选并同意相关协议');store.set('privacy',true);modal.innerHTML='';return}const copy=e.target.closest('[data-copy]');if(copy){navigator.clipboard?.writeText(location.origin+location.pathname+'?code='+copy.dataset.copy);toast('邀请链接已复制');return}if(e.target.closest('[data-qr]')){toast('部署域名后可生成网页二维码');return}if(e.target.closest('[data-list]'))toast('当前场次暂无邀请记录')});
document.addEventListener('change',e=>{if(e.target.id==='count')renderGuests(Number(e.target.value),state.profile||{})});
document.addEventListener('submit',e=>{if(e.target.id!=='applyForm')return;e.preventDefault();const f=new FormData(e.target),n=Number(document.getElementById('count').value),guests=[];for(let i=0;i<n;i++){const phone=String(f.get('phone'+i)||'');if(!/^1\d{10}$/.test(phone))return toast(`第${i+1}位手机号有误`);guests.push({name:f.get('name'+i),company:f.get('company'+i),gender:f.get('gender'+i),phone,position:f.get('position'+i),stay:f.get('stay'+i)})}state.profile={name:guests[0].name,gender:guests[0].gender,phone:guests[0].phone};state.application={city:state.city,status:'PENDING',guests,reason:f.get('reason')};store.set('profile',state.profile);store.set('application',state.application);applicationResult()});
document.addEventListener('click',e=>{if(e.target.id!=='draw')return;if(!state.application||state.application.status!=='APPROVED')return toast('参会登记审核通过后方可领取抽奖码');const machine=document.getElementById('machine'),reels=[...document.querySelectorAll('.reel')];machine.classList.add('running');e.target.disabled=true;e.target.textContent='摇号中 ···';let ticks=0;const timer=setInterval(()=>{reels.forEach((r,i)=>{if(ticks<20+i*5)r.textContent=Math.floor(Math.random()*10)});if(++ticks>38){clearInterval(timer);state.lucky=String(Math.floor(Math.random()*10000)).padStart(4,'0');store.set('lucky',state.lucky);reels.forEach((r,i)=>setTimeout(()=>r.textContent=state.lucky[i],i*180));setTimeout(()=>{machine.classList.remove('running');machine.classList.add('reveal');document.querySelector('.result-seal').textContent='LUCKY';document.getElementById('notice').textContent='您的抽奖码已经生成，等待开奖。';e.target.textContent='号码已抽取'},1100)}},70)});
window.addEventListener('hashchange',route);route();
})();
